/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gui;

import java.awt.Dimension;

/**
 *
 * @author Николай
 */
public class InputRouteUI extends javax.swing.JFrame {

    /**
     * Creates new form f2
     */
    public InputRouteUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        pnlCar = new javax.swing.JPanel();
        cmbSelectCar = new javax.swing.JComboBox();
        btnAllCars = new javax.swing.JButton();
        btnAddCar = new javax.swing.JButton();
        lblSelectCar = new javax.swing.JLabel();
        pnlRoute = new javax.swing.JPanel();
        pnlMyRoutes = new javax.swing.JPanel();
        cmbListRoutes = new javax.swing.JComboBox();
        lblListRoutes = new javax.swing.JLabel();
        btnDeleteRoute = new javax.swing.JButton();
        btnAddRoute = new javax.swing.JButton();
        btnEditRoute = new javax.swing.JButton();
        pnlNewRoute = new javax.swing.JPanel();
        lblRouteName = new javax.swing.JLabel();
        lblCountry = new javax.swing.JLabel();
        lblCity = new javax.swing.JLabel();
        lblStreet = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox();
        lblHouse = new javax.swing.JLabel();
        lblCurRoute = new javax.swing.JLabel();
        scrCurRoute = new javax.swing.JScrollPane();
        txaCurRoute = new javax.swing.JTextArea();
        btnBuildOptimalRoute = new javax.swing.JButton();

        jDialog1.setMinimumSize(new java.awt.Dimension(100, 110));
        jDialog1.setModal(true);

        jButton1.setText("jButton1");
        jButton1.setMaximumSize(null);
        jButton1.setMinimumSize(new java.awt.Dimension(100, 100));
        jButton1.setPreferredSize(new java.awt.Dimension(100, 100));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialog1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialog1Layout.createSequentialGroup()
                .addContainerGap(122, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(140, 140, 140))
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jLabel1)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Пошук оптимального маршруту - Вибір автомобіля, маршруту");
        setMinimumSize(new java.awt.Dimension(793, 509));

        pnlCar.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Дані про автомобіль"));

        cmbSelectCar.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Вибір зі списку", "Item 2", "Item 3", "Item 4" }));

        btnAllCars.setText("Повна інформація");

        btnAddCar.setText("Додати автомобіль");

        lblSelectCar.setText("Обрати автомобіль зі списку");

        javax.swing.GroupLayout pnlCarLayout = new javax.swing.GroupLayout(pnlCar);
        pnlCar.setLayout(pnlCarLayout);
        pnlCarLayout.setHorizontalGroup(
            pnlCarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSelectCar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 144, Short.MAX_VALUE)
                .addComponent(cmbSelectCar, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(btnAllCars)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAddCar, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlCarLayout.setVerticalGroup(
            pnlCarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbSelectCar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAllCars)
                    .addComponent(btnAddCar)
                    .addComponent(lblSelectCar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlRoute.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Дані про маршрут"));

        pnlMyRoutes.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Мої маршрути", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        cmbListRoutes.setEditable(true);
        cmbListRoutes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbListRoutes.setMinimumSize(new java.awt.Dimension(6, 20));
        cmbListRoutes.setPreferredSize(new java.awt.Dimension(10, 20));

        lblListRoutes.setText("Вибір маршруту зі списку збережених");

        btnDeleteRoute.setText("Видалити");

        btnAddRoute.setText("Додати новий ");

        btnEditRoute.setText("Редагувати");
        btnEditRoute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditRouteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlMyRoutesLayout = new javax.swing.GroupLayout(pnlMyRoutes);
        pnlMyRoutes.setLayout(pnlMyRoutesLayout);
        pnlMyRoutesLayout.setHorizontalGroup(
            pnlMyRoutesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMyRoutesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblListRoutes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbListRoutes, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditRoute)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDeleteRoute)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAddRoute)
                .addContainerGap())
        );
        pnlMyRoutesLayout.setVerticalGroup(
            pnlMyRoutesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMyRoutesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMyRoutesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblListRoutes)
                    .addComponent(btnDeleteRoute)
                    .addComponent(btnAddRoute)
                    .addComponent(btnEditRoute)
                    .addComponent(cmbListRoutes, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pnlNewRoute.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Новий маршрут", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        lblRouteName.setText("Назва маршруту");

        lblCountry.setText("Країна");

        lblCity.setText("Місто");

        lblStreet.setText("Вулиця");

        jComboBox3.setEditable(true);
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblHouse.setText("Номер будинку");

        lblCurRoute.setText("Поточний введений маршрут:");

        txaCurRoute.setColumns(20);
        txaCurRoute.setRows(5);
        txaCurRoute.setEnabled(false);
        scrCurRoute.setViewportView(txaCurRoute);

        btnBuildOptimalRoute.setText("Побудова оптмального маршруту");

        javax.swing.GroupLayout pnlNewRouteLayout = new javax.swing.GroupLayout(pnlNewRoute);
        pnlNewRoute.setLayout(pnlNewRouteLayout);
        pnlNewRouteLayout.setHorizontalGroup(
            pnlNewRouteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNewRouteLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(pnlNewRouteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlNewRouteLayout.createSequentialGroup()
                        .addGroup(pnlNewRouteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRouteName)
                            .addComponent(lblCity))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlNewRouteLayout.createSequentialGroup()
                        .addGroup(pnlNewRouteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCountry)
                            .addComponent(lblCurRoute)
                            .addGroup(pnlNewRouteLayout.createSequentialGroup()
                                .addComponent(lblHouse)
                                .addGap(152, 152, 152)
                                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(scrCurRoute, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlNewRouteLayout.createSequentialGroup()
                        .addComponent(lblStreet)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBuildOptimalRoute)
                        .addGap(80, 80, 80))))
        );
        pnlNewRouteLayout.setVerticalGroup(
            pnlNewRouteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNewRouteLayout.createSequentialGroup()
                .addComponent(lblRouteName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCountry)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCity)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlNewRouteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStreet)
                    .addComponent(btnBuildOptimalRoute))
                .addGap(5, 5, 5)
                .addGroup(pnlNewRouteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblHouse)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addComponent(lblCurRoute)
                .addGap(18, 18, 18)
                .addComponent(scrCurRoute, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlRouteLayout = new javax.swing.GroupLayout(pnlRoute);
        pnlRoute.setLayout(pnlRouteLayout);
        pnlRouteLayout.setHorizontalGroup(
            pnlRouteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRouteLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(pnlRouteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlMyRoutes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlNewRoute, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlRouteLayout.setVerticalGroup(
            pnlRouteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRouteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlMyRoutes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlNewRoute, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlRoute, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlCar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlCar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlRoute, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditRouteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditRouteActionPerformed
        this.setMinimumSize(new Dimension(3,3));
        Dimension small =new Dimension(this.getWidth(),250);
        this.setSize(small);
        this.pnlNewRoute.setVisible(false);
        this.jDialog1.setVisible(true);
    }//GEN-LAST:event_btnEditRouteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.jDialog1.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InputRouteUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InputRouteUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InputRouteUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InputRouteUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InputRouteUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCar;
    private javax.swing.JButton btnAddRoute;
    private javax.swing.JButton btnAllCars;
    private javax.swing.JButton btnBuildOptimalRoute;
    private javax.swing.JButton btnDeleteRoute;
    private javax.swing.JButton btnEditRoute;
    private javax.swing.JComboBox cmbListRoutes;
    private javax.swing.JComboBox cmbSelectCar;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblCountry;
    private javax.swing.JLabel lblCurRoute;
    private javax.swing.JLabel lblHouse;
    private javax.swing.JLabel lblListRoutes;
    private javax.swing.JLabel lblRouteName;
    private javax.swing.JLabel lblSelectCar;
    private javax.swing.JLabel lblStreet;
    private javax.swing.JPanel pnlCar;
    private javax.swing.JPanel pnlMyRoutes;
    private javax.swing.JPanel pnlNewRoute;
    private javax.swing.JPanel pnlRoute;
    private javax.swing.JScrollPane scrCurRoute;
    private javax.swing.JTextArea txaCurRoute;
    // End of variables declaration//GEN-END:variables
}
