/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gui;
import controllers.LogInController;
import java.awt.Color;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.text.AbstractDocument;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;
/**
 *
 * @author Николай
 */
public class LogInUI extends javax.swing.JFrame {
    private LogInController loginControl;
    private Color errorMess=new Color(255,0,51);
    private int lenghtTxt=16;
    public LogInUI() throws ParseException {
        initComponents();
        loginControl=new LogInController();
        btnLogIn.addActionListener(loginControl);
        
        btnLogIn.setEnabled(false);
        jButton1.setEnabled(false);
        AbstractDocument doc = (AbstractDocument) txtPassword.getDocument();
        doc.setDocumentFilter(new LengthFilter(doc.getLength(), lenghtTxt));
        //AbstractDocument doc2 = (AbstractDocument) txtPassword.getDocument();
        //doc2.setDocumentFilter(new LengthFilter(doc2.getLength(), lenghtTxt));
        
        MaskFormatter loginMask=new MaskFormatter("?AAAAAAAAAAAAAAA");
        DefaultFormatterFactory formatterFactory 
                = new DefaultFormatterFactory(loginMask);
        ftxLogin.setFormatterFactory(formatterFactory);
        ftxLogin1.setFormatterFactory(formatterFactory);
        
        MaskFormatter driverMask=new MaskFormatter("UUU-######");
        DefaultFormatterFactory formatterFactory2 
                = new DefaultFormatterFactory(driverMask);
        jFormattedTextField1.setFormatterFactory(formatterFactory2);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jPasswordField2 = new javax.swing.JPasswordField();
        lblLogin1 = new javax.swing.JLabel();
        ftxLogin1 = new javax.swing.JFormattedTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        lblPass1Status = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblLogin1Status = new javax.swing.JLabel();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        lblPass2Status = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        pnlAutorization = new javax.swing.JPanel();
        lblLogin = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        btnLogIn = new javax.swing.JButton();
        btnSignIn = new javax.swing.JButton();
        txtPassword = new javax.swing.JPasswordField();
        lblLoginStatus = new javax.swing.JLabel();
        ftxLogin = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        lblPassStatus = new javax.swing.JLabel();

        jDialog1.setTitle("Пошук оптимального маршруту - Реєстрація в системі");
        jDialog1.setLocationByPlatform(true);
        jDialog1.setMinimumSize(new java.awt.Dimension(344, 326));
        jDialog1.setModal(true);
        jDialog1.setResizable(false);
        jDialog1.setType(java.awt.Window.Type.UTILITY);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPasswordField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordField2FocusLost(evt);
            }
        });
        jPasswordField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPasswordField2KeyReleased(evt);
            }
        });

        lblLogin1.setText("Введіть логін:");

        ftxLogin1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        ftxLogin1.setFocusLostBehavior(javax.swing.JFormattedTextField.PERSIST);
        ftxLogin1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ftxLogin1FocusGained(evt);
            }
        });
        ftxLogin1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ftxLogin1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ftxLogin1KeyReleased(evt);
            }
        });

        jPasswordField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPasswordField1KeyReleased(evt);
            }
        });

        jLabel4.setText("Введіть пароль");

        jFormattedTextField1.setFocusLostBehavior(javax.swing.JFormattedTextField.PERSIST);
        jFormattedTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jFormattedTextField1FocusLost(evt);
            }
        });

        jLabel5.setText("Серія та номер водійського посвідчення:");

        jButton1.setText("Реєстрація");

        jLabel2.setText("Підтвердіть пароль");
        jLabel2.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblLogin1)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jFormattedTextField1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPasswordField2)
                                    .addComponent(jPasswordField1)
                                    .addComponent(ftxLogin1, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPass2Status)
                                    .addComponent(lblLogin1Status)
                                    .addComponent(lblPass1Status)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(jButton1)))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLogin1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ftxLogin1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLogin1Status))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPass1Status))
                .addGap(11, 11, 11)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPass2Status))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Пошук оптимального маршруту - Авторизація");
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(339, 162));
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);

        pnlAutorization.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlAutorization.setMaximumSize(new java.awt.Dimension(319, 140));
        pnlAutorization.setMinimumSize(new java.awt.Dimension(319, 140));

        lblLogin.setLabelFor(ftxLogin);
        lblLogin.setText("Логін");
        lblLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblPassword.setText("Пароль");

        btnLogIn.setText("Авторизація");
        btnLogIn.setActionCommand("login");
        btnLogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogInActionPerformed(evt);
            }
        });

        btnSignIn.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        btnSignIn.setText("Реєстрація");
        btnSignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignInActionPerformed(evt);
            }
        });

        txtPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPasswordKeyReleased(evt);
            }
        });

        lblLoginStatus.setLabelFor(ftxLogin);

        ftxLogin.setFocusLostBehavior(javax.swing.JFormattedTextField.PERSIST);
        ftxLogin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ftxLoginFocusGained(evt);
            }
        });
        ftxLogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ftxLoginKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ftxLoginKeyReleased(evt);
            }
        });

        jLabel1.setText("Не заререєстровані у системі?");

        lblPassStatus.setText(" ");

        javax.swing.GroupLayout pnlAutorizationLayout = new javax.swing.GroupLayout(pnlAutorization);
        pnlAutorization.setLayout(pnlAutorizationLayout);
        pnlAutorizationLayout.setHorizontalGroup(
            pnlAutorizationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAutorizationLayout.createSequentialGroup()
                .addGroup(pnlAutorizationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAutorizationLayout.createSequentialGroup()
                        .addGroup(pnlAutorizationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlAutorizationLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblPassword))
                            .addGroup(pnlAutorizationLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(lblLogin)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlAutorizationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnLogIn)
                            .addGroup(pnlAutorizationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(ftxLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                                .addComponent(txtPassword)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlAutorizationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPassStatus)
                            .addComponent(lblLoginStatus))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAutorizationLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                        .addComponent(btnSignIn)))
                .addContainerGap())
        );
        pnlAutorizationLayout.setVerticalGroup(
            pnlAutorizationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAutorizationLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAutorizationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ftxLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLoginStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlAutorizationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPassword)
                    .addGroup(pnlAutorizationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblPassStatus)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLogIn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlAutorizationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSignIn)
                    .addComponent(jLabel1))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlAutorization, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlAutorization, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogInActionPerformed
        this.hide();
    }//GEN-LAST:event_btnLogInActionPerformed
    private int lengthMaskString(String s){
        return s.indexOf(" ")!=-1 ? s.indexOf(" "):s.length();
    }
    private void ftxLoginKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ftxLoginKeyReleased
        int lengthLogin= lengthMaskString(ftxLogin.getText()); 
        if(ftxLogin.getCaretPosition()>lengthLogin)
            ftxLogin.setCaretPosition(lengthLogin);
        if(lengthLogin<3){
            lblLoginStatus.setForeground(errorMess);
            lblLoginStatus.setText("Не менше 3 знаків!");
        }
        else 
            lblLoginStatus.setText("");
        btnLogInIsVisible();
    }//GEN-LAST:event_ftxLoginKeyReleased

    private void ftxLoginFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ftxLoginFocusGained
        lblLoginStatus.setText("");
    }//GEN-LAST:event_ftxLoginFocusGained

    private void btnSignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignInActionPerformed
        this.jDialog1.setVisible(true);
    }//GEN-LAST:event_btnSignInActionPerformed

    private void ftxLoginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ftxLoginKeyPressed
        int lengthLogin= lengthMaskString(ftxLogin.getText()); 
        if(ftxLogin.getCaretPosition()>lengthLogin)
            ftxLogin.setCaretPosition(lengthLogin);
    }//GEN-LAST:event_ftxLoginKeyPressed

    private void ftxLogin1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ftxLogin1FocusGained
        lblLoginStatus.setText("");
    }//GEN-LAST:event_ftxLogin1FocusGained

    private void ftxLogin1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ftxLogin1KeyPressed
        int lengthLogin= lengthMaskString(ftxLogin.getText());
        if(ftxLogin.getCaretPosition()>lengthLogin)
        ftxLogin.setCaretPosition(lengthLogin);
    }//GEN-LAST:event_ftxLogin1KeyPressed

    private void ftxLogin1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ftxLogin1KeyReleased
        int lengthLogin= lengthMaskString(ftxLogin1.getText());
        //jLabel4.setText(
            //new Integer(ftxLogin.getCaretPosition()).toString());
        if(ftxLogin1.getCaretPosition()>lengthLogin)
        ftxLogin1.setCaretPosition(lengthLogin);
        if(lengthLogin<3){
            lblLogin1Status.setForeground(errorMess);
            lblLogin1Status.setText("Не менше 3-х символів!");
        }
        else
            lblLogin1Status.setText("");
        
    }//GEN-LAST:event_ftxLogin1KeyReleased

    private void txtPasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPasswordKeyReleased
        if(txtPassword.getText().length()<3){
            lblPassStatus.setForeground(errorMess);
            lblPassStatus.setText("Не менше 3 знаків!");
        }
        else
            lblPassStatus.setText("");
        btnLogInIsVisible();
    }//GEN-LAST:event_txtPasswordKeyReleased

    private void jPasswordField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField1KeyReleased
        if(jPasswordField1.getText().length()<3){
            lblPass1Status.setForeground(errorMess);
            lblPass1Status.setText("Не менше 3-х символів!");
        }
        else{
            lblPass1Status.setText("");
            equalPass();
        }
        btnSignInIsVisible();
    }//GEN-LAST:event_jPasswordField1KeyReleased

    private void jPasswordField2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField2KeyReleased
        if(jPasswordField2.getText().length()<3){
            lblPass2Status.setForeground(errorMess);
            lblPass2Status.setText("Не менше 3-х символів!");
        }
        else{
            lblPass2Status.setText("");
            equalPass();
        }
        btnSignInIsVisible();
    }//GEN-LAST:event_jPasswordField2KeyReleased

    private void jPasswordField2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField2FocusLost
        equalPass();
        btnSignInIsVisible();
    }//GEN-LAST:event_jPasswordField2FocusLost

    private void jFormattedTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFormattedTextField1FocusLost
        btnSignInIsVisible();
    }//GEN-LAST:event_jFormattedTextField1FocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogInUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogInUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogInUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogInUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new LogInUI().setVisible(true);
                } catch (ParseException ex) {
                    Logger.getLogger(LogInUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogIn;
    private javax.swing.JButton btnSignIn;
    private javax.swing.JFormattedTextField ftxLogin;
    private javax.swing.JFormattedTextField ftxLogin1;
    private javax.swing.JButton jButton1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblLogin1;
    private javax.swing.JLabel lblLogin1Status;
    private javax.swing.JLabel lblLoginStatus;
    private javax.swing.JLabel lblPass1Status;
    private javax.swing.JLabel lblPass2Status;
    private javax.swing.JLabel lblPassStatus;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JPanel pnlAutorization;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables

    private boolean checkLogInFields() {
        if(lengthMaskString(ftxLogin.getText())>=3 && txtPassword.getText().length()>=3)
            return true;
        return false;
    }

    private void btnLogInIsVisible() {
        if(checkLogInFields())
            btnLogIn.setEnabled(true);
        else 
            btnLogIn.setEnabled(false);
    }

    private void btnSignInIsVisible() {
        if(checkSignInFields())
            jButton1.setEnabled(true);
        else 
            jButton1.setEnabled(false);
    }

    private boolean checkSignInFields() {
        if(lengthMaskString(ftxLogin1.getText())>=3 && 
                jPasswordField1.getText().length()>=3 &&
                jPasswordField2.getText().length()>=3  &&
                jPasswordField1.getText().equals(jPasswordField2.getText()) &&
                jFormattedTextField1.isValid()) 
            return true;
        return false;
    }
    private void equalPass(){
        if(jPasswordField2.getText().length()>=3 &&
                !jPasswordField2.getText().equals(jPasswordField1.getText())){
            lblPass2Status.setForeground(errorMess);
            lblPass2Status.setText("Паролі не співпадають!");
        }
        else
            lblPass2Status.setText("");
    }
}
