/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gui;
import controllers.LogInController;
import java.awt.Color;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.text.AbstractDocument;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;
/**
 *
 * @author Николай
 */
public class LogInUI extends javax.swing.JFrame {
    private LogInController loginControl;
    private Color errorMess=new Color(255,0,51);
    public LogInUI() throws ParseException {
        initComponents();
        loginControl=new LogInController();
        btnLogIn.addActionListener(loginControl);
        /*AbstractDocument doc = (AbstractDocument) txtLogin.getDocument();
        doc.setDocumentFilter(new LengthFilter(doc.getLength(), lengthLogin));
        AbstractDocument doc2 = (AbstractDocument) txtPassword.getDocument();
        doc2.setDocumentFilter(new LengthFilter(doc2.getLength(), lengthLogin));*/
        
        MaskFormatter loginMask=new MaskFormatter("?AAAAAAAAAAAAAAA");
        DefaultFormatterFactory formatterFactory 
                = new DefaultFormatterFactory(loginMask);
        ftxLogin.setFormatterFactory(formatterFactory);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlAutorization = new javax.swing.JPanel();
        lblLogin = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        btnLogIn = new javax.swing.JButton();
        btnSignIn = new javax.swing.JButton();
        txtPassword = new javax.swing.JPasswordField();
        lblLoginStatus = new javax.swing.JLabel();
        ftxLogin = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Пошук оптимального маршруту - Авторизація");
        setType(java.awt.Window.Type.UTILITY);

        pnlAutorization.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblLogin.setLabelFor(ftxLogin);
        lblLogin.setText("Логін");
        lblLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblPassword.setText("Пароль");

        btnLogIn.setText("Авторизація");
        btnLogIn.setActionCommand("login");
        btnLogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogInActionPerformed(evt);
            }
        });

        btnSignIn.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        btnSignIn.setText("Реєстрація");
        btnSignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignInActionPerformed(evt);
            }
        });

        lblLoginStatus.setLabelFor(ftxLogin);

        ftxLogin.setFocusLostBehavior(javax.swing.JFormattedTextField.PERSIST);
        ftxLogin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ftxLoginFocusGained(evt);
            }
        });
        ftxLogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ftxLoginKeyReleased(evt);
            }
        });

        jLabel1.setText("Не заререєстровані у системі?");

        javax.swing.GroupLayout pnlAutorizationLayout = new javax.swing.GroupLayout(pnlAutorization);
        pnlAutorization.setLayout(pnlAutorizationLayout);
        pnlAutorizationLayout.setHorizontalGroup(
            pnlAutorizationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAutorizationLayout.createSequentialGroup()
                .addGroup(pnlAutorizationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAutorizationLayout.createSequentialGroup()
                        .addGroup(pnlAutorizationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlAutorizationLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblPassword))
                            .addGroup(pnlAutorizationLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(lblLogin)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlAutorizationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnLogIn)
                            .addGroup(pnlAutorizationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(ftxLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                                .addComponent(txtPassword)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblLoginStatus)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAutorizationLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                        .addComponent(btnSignIn)))
                .addContainerGap())
        );
        pnlAutorizationLayout.setVerticalGroup(
            pnlAutorizationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAutorizationLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAutorizationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ftxLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLoginStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlAutorizationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPassword)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLogIn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlAutorizationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSignIn)
                    .addComponent(jLabel1))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlAutorization, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlAutorization, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogInActionPerformed
        this.hide();
    }//GEN-LAST:event_btnLogInActionPerformed
    private int lengthMaskString(String s){
        return s.indexOf(" ")!=-1 ? s.indexOf(" "):s.length();
    }
    private void ftxLoginKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ftxLoginKeyReleased
        int lengthLogin= lengthMaskString(ftxLogin.getText()); 
        if(lengthLogin<3){
            lblLoginStatus.setForeground(errorMess);
            lblLoginStatus.setText("Не менше 3 знаків!");
        }
        else 
            lblLoginStatus.setText("");
        //lblLoginStatus.setText();
    }//GEN-LAST:event_ftxLoginKeyReleased

    private void ftxLoginFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ftxLoginFocusGained
        lblLoginStatus.setText("");
    }//GEN-LAST:event_ftxLoginFocusGained

    private void btnSignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignInActionPerformed
        //lblLoginStatus.setText(ftxLogin.getText());
    }//GEN-LAST:event_btnSignInActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogInUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogInUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogInUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogInUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new LogInUI().setVisible(true);
                } catch (ParseException ex) {
                    Logger.getLogger(LogInUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogIn;
    private javax.swing.JButton btnSignIn;
    private javax.swing.JFormattedTextField ftxLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblLoginStatus;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JPanel pnlAutorization;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables
}
